name : date

on: push

jobs:
    Job1:
        name: Job1
        runs-on: ubuntu-latest
        steps:
             - name: step one
               uses: actions/checkout@v2
             - name: step two
               run: printf "%s\n" "$now"
    Job2:
        name: Job2
        runs-on: windows-latest
        steps:
             - name: step one
               uses: actions/checkout@v2
             - name: step two
               run: printf "%s\n" "$now"       
    Job3:
        name: Job3                
        runs-on: macos-latest
        steps:
             - name: step one
               uses: actions/checkout@v2
             - name: step two
               run: printf "%s\n" "$now"
    Job4:
        name: Fourth job
        needs: [Job1,Job2,Job3]
        runs-on: windows-latest
        steps:
             - run: printf "%s\n" "$now"























 
  
   
    
     
      
       
         
            
             
